app/urls.py
from django.urls import path
from .views import (
    homeView,
)
from .authentication import (
    loginPage,
    logoutUser,
)
app_name = 'app'

urlpatterns = [
    path('', homeView, name='home'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='app:login')
def homeView(request):


    context = {}
    return render(request, 'app/home.html', context)

app/templates/app/home.html
{% extends 'main.html' %}
{% block content %}
<h2> Home Page!</h2>
{% endblock content %}

app/templates/app/login.html
{% extends 'main.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'styles/login.css' %}">
{% endblock styles %}
{% block content %}
<main class="content px-3 py-2">
    <div class="form-login">
        <form method="POST", action="">
            {% csrf_token %}
            <div class="wrapper-login">
                <h1>Login</h1>
                <div class="input-box">
                    <input type="text" name="username" placeholder="Username" required>
                    <i class="bx bxs-user"></i>
                </div>
                <div class="input-box">
                    <input type="password" name="password"
                    placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" required>
                    <i class="bx bxs-lock-alt"></i>
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox">Remember me</label>
                    <a href="#">Forgot password?</a>
                </div>
                <button type="submit" class="btn btn-warning">Login</button>

                <div class="register-link">
                    <p>Don't have a account?
                        <a href="#">Register</a>
                    </p>
                </div>
            </div>
        </form>
    </div>
</main>

{% endblock content %}

templates/alerts.html
<!-- Bootstrap Alerts rendered message under navbar -->
<div class="row p-2 text-center">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <!--span aria-hidden="true">&times;</span-->
        </button>
        {{ message | safe }}
    </div>
    {% endfor %}
</div>

templates/footer.html
{% if request.user.is_authenticated %}
<!-- Start Footer -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-start">
                <p class="mb-0">
                    <a href="#" class="text-muted">
                        <strong>@devMotcho</strong>
                    </a>
                </p>
            </div>
            <div class="col-6 text-end">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">dev.mmd2@gmail.com</a>
                    </li>
                    <li class="list-inline-item">
                        &copy; Copyright 2024 Motcho
                    </li>
                    <!-- <li class="list-inline-item">
                        <a href="#" class="text-muted">About Us</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">Terms</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">Booking</a> -->
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- End Footer -->
{% endif %}

templates/main.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="dark">

<head>
    <!-- Meta data -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Tags -->
    <title>{% block title %} {% endblock title %}</title>
    {% block scripts %} {% endblock scripts %}
    {% block styles %} {% endblock styles %}

    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">

    <!-- Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/af0ff4f1fc.js" crossorigin="anonymous"></script>

    <!-- Chart Js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
    <div class="wrapper">
        {% include 'sidebar.html' %}
        <div class="main">
            {% include 'navbar.html' %}
            {% include 'alerts.html' %}
            {% block content %}
            {% endblock content %}
            {% include 'theme.html' %}
            {% include 'footer.html' %}
        </div>
    </div>


    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/navbar.html
{% load static %}
{% if request.user.is_authenticated %}
<nav class="navbar navbar-expand px-3 border-bottom">
    <!-- Toggle SideBar -->
    <button class="btn" id="sidebar-toggle" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Search with q -->
    <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
     
    <!-- Dropdown settings -->
    <div class="navbar-collapse navbar">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a href="#" data-bs-toggle="dropdown" class="nav-icon pe-md-5 mx-4">
                    <i class=" fa-solid fa-gear"></i>
                    <!-- <img src="{{user.profile.avatar.url}}" class="avatar img-fluid rounded" alt=""> -->
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a href="#" class="dropdown-item"><i class="fa-solid fa-user"></i> Profile</a>
                    <a href="#" class="dropdown-item"><i class="fa-solid fa-gears"></i> Settings </a>
                    <a href="{% url 'app:logout' %}" class="dropdown-item"><i class="fa-solid fa-door-open"></i>
                        Logout</a>
                </div>
            </li>
        </ul>
    </div>
    <!-- End Dropdown settings -->
</nav>
{% endif %}

templates/sidebar.html
{% if request.user.is_authenticated %}
<aside id="sidebar" class="js-sidebar">
    <!-- Content for sidebar -->
    <div class="h-100">
        <div class="sidebar-logo bg-secondary text-center text-warning">
            <a href="{% url 'app:home' %}">Motcho</a>
        </div>
        <ul class="sidebar-nav">
            <li class="sidebar-header">
            </li>
            <hr>
            <!-- Home -->
            <li class="sidebar-item">
                <a href="{% url 'app:home' %}" class="sidebar-link">
                    <i class="fa-solid fa-house"></i>
                    Home
                </a>
            </li>
            <hr>
        </ul>
    </div>
</aside>
{% endif %}

templates/theme.html
{% if request.user.is_authenticated %}
<a href="#" class="theme-toggle">
    <i class="fa-regular fa-moon"></i>
    <i class="fa-regular fa-sun"></i>
</a>
{% endif %}